# Generated by Django 2.2 on 2020-04-30 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('maintainer', 'maintainer'), ('guest', 'guest')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('codename', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(through='api_doc.Membership', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_doc.Project'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GitHook',
            fields=[
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('git_repo', models.CharField(max_length=255)),
                ('doc_path', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_doc.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc', to='api_doc.Project')),
            ],
        ),
    ]
