# Generated by Django 2.2 on 2020-04-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='path',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
